### PR TITLE
Switch to prime-order subgroup

### LINKED ISSUE #9: Switch the verifier to use a prime-order subgroup
## Generic Issue

**Description**
Switch the verifier to use a prime-order subgroup for exponents, as specified in the final version of the ElectionGuard spec. (Current master instead uses the group mod p-1, as specified in a previous draft of the spec.) The primes used in this branch are the same ones from the encryption SDK (specifically bignum.c).

### PR DESCRIPTION
**Pull request by spernsteiner**
This branch switches the verifier to use a prime-order subgroup for exponents, as specified in the final version of the ElectionGuard spec.  (Current master instead uses the group mod `p-1`, as specified in a previous draft of the spec.)  The primes used in this branch are the same ones from the encryption SDK (specifically [bignum.c](https://github.com/microsoft/electionguard-c/blob/master/src/electionguard/bignum.c)).  This branch also adds some checks from the spec that were previously not implementable due to the exponent group having non-prime order.

To run the tests:
```
cargo test --lib --release --feature test-big-primes
```
The `--feature test-big-primes` causes tests to use the real, full-sized primes from the spec, instead of the small primes that allow for quick test runs.  When using the full-size primes, `--release` is highly recommended, since computing with such large values is quite slow in debug builds.

Fixes #9

### CODE REVIEW

**Comment by spernsteiner** [comment]
I believe this work is covered under our previous contract.  I've done some cleanup to allow rebasing against current master and switched out the primes, but the vast majority of this code is copied from [this branch](https://github.com/spernsteiner/electionguard-verifier/tree/prime-order-subgroup) of the original development.  If you think the CLA is still necessary, please let me know and I'll check with our legal team.

**Comment by spernsteiner** [comment]
@echumley-msft ping - not sure if you got the notification when I opened the PR.  This is the branch we discussed yesterday for updating the verifier to use the same parameters as the encryption SDK.

**Review by AddressXception — APPROVED** [review]

**Comment by echumley-msft** [comment]
Hey @spernsteiner - would you mind signing the CLA agreement? (Linked in the PR above) I can't merge this in until that's complete. Thanks!

**Comment by spernsteiner** [comment]
I'm currently waiting to hear back from our legal team on whether I can sign that CLA.  (Though, as mentioned above, I don't think it should be necessary in this case.)  I should have an update for you by Monday.

**Pull request closed without merging**
